// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubscriberAPI.Data;

#nullable disable

namespace SubscriberAPI.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20220407120456_IntitialCreate")]
    partial class IntitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SubscriberAPI.Models.AddressModel", b =>
                {
                    b.Property<int>("Ad_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ad_Id"), 1L, 1);

                    b.Property<string>("Ad_City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ad_PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Ad_Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Su_Id")
                        .HasColumnType("int");

                    b.HasKey("Ad_Id");

                    b.HasIndex("Su_Id")
                        .IsUnique();

                    b.ToTable("Tbl_Address");
                });

            modelBuilder.Entity("SubscriberAPI.Models.SubscriberModel", b =>
                {
                    b.Property<int>("Su_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Su_Id"), 1L, 1);

                    b.Property<string>("Su_FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Su_LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Su_PersonId")
                        .HasColumnType("int");

                    b.HasKey("Su_Id");

                    b.ToTable("Tbl_Subscribers");
                });

            modelBuilder.Entity("SubscriberAPI.Models.AddressModel", b =>
                {
                    b.HasOne("SubscriberAPI.Models.SubscriberModel", "Subscriber")
                        .WithOne("Su_Adress")
                        .HasForeignKey("SubscriberAPI.Models.AddressModel", "Su_Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("SubscriberAPI.Models.SubscriberModel", b =>
                {
                    b.Navigation("Su_Adress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
