// <auto-generated />
using AdvertSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdvertSystem.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20220407132943_IntialCreate")]
    partial class IntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AdvertSystem.Models.AddressModel", b =>
                {
                    b.Property<int>("Ad_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ad_Id"), 1L, 1);

                    b.Property<string>("Ad_City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ad_PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Ad_Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ad_Id");

                    b.ToTable("Tbl_Address");
                });

            modelBuilder.Entity("AdvertSystem.Models.AdModel", b =>
                {
                    b.Property<int>("Ads_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ads_Id"), 1L, 1);

                    b.Property<int>("Ads_AnnonsorAn_Id")
                        .HasColumnType("int");

                    b.Property<string>("Ads_Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ads_Price")
                        .HasColumnType("int");

                    b.Property<int>("Ads_ProductPrice")
                        .HasColumnType("int");

                    b.Property<string>("Ads_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ads_Id");

                    b.HasIndex("Ads_AnnonsorAn_Id");

                    b.ToTable("Tbl_Ads");
                });

            modelBuilder.Entity("AdvertSystem.Models.AnnonsorerModel", b =>
                {
                    b.Property<int>("An_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("An_Id"), 1L, 1);

                    b.Property<int>("An_CoIdCo_OrgId")
                        .HasColumnType("int");

                    b.Property<int>("An_SubId")
                        .HasColumnType("int");

                    b.HasKey("An_Id");

                    b.HasIndex("An_CoIdCo_OrgId");

                    b.ToTable("Tbl_Annonsorer");
                });

            modelBuilder.Entity("AdvertSystem.Models.CompanyModel", b =>
                {
                    b.Property<int>("Co_OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Co_OrgId"), 1L, 1);

                    b.Property<int>("Co_AddressAd_Id")
                        .HasColumnType("int");

                    b.Property<int>("Co_BillingAddressAd_Id")
                        .HasColumnType("int");

                    b.Property<string>("Co_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Co_Telephone")
                        .HasColumnType("int");

                    b.HasKey("Co_OrgId");

                    b.HasIndex("Co_AddressAd_Id");

                    b.HasIndex("Co_BillingAddressAd_Id");

                    b.ToTable("Tbl_Companies");
                });

            modelBuilder.Entity("AdvertSystem.Models.AdModel", b =>
                {
                    b.HasOne("AdvertSystem.Models.AnnonsorerModel", "Ads_Annonsor")
                        .WithMany()
                        .HasForeignKey("Ads_AnnonsorAn_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ads_Annonsor");
                });

            modelBuilder.Entity("AdvertSystem.Models.AnnonsorerModel", b =>
                {
                    b.HasOne("AdvertSystem.Models.CompanyModel", "An_CoId")
                        .WithMany()
                        .HasForeignKey("An_CoIdCo_OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("An_CoId");
                });

            modelBuilder.Entity("AdvertSystem.Models.CompanyModel", b =>
                {
                    b.HasOne("AdvertSystem.Models.AddressModel", "Co_Address")
                        .WithMany()
                        .HasForeignKey("Co_AddressAd_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdvertSystem.Models.AddressModel", "Co_BillingAddress")
                        .WithMany()
                        .HasForeignKey("Co_BillingAddressAd_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Co_Address");

                    b.Navigation("Co_BillingAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
