// <auto-generated />
using System;
using AdvertSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdvertSystem.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AdvertSystem.Models.AdModel", b =>
                {
                    b.Property<int>("Ads_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ads_Id"), 1L, 1);

                    b.Property<int>("Ads_AnnonsorAn_Id")
                        .HasColumnType("int");

                    b.Property<string>("Ads_Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ads_Price")
                        .HasColumnType("int");

                    b.Property<int>("Ads_ProductPrice")
                        .HasColumnType("int");

                    b.Property<string>("Ads_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ads_Id");

                    b.HasIndex("Ads_AnnonsorAn_Id");

                    b.ToTable("Tbl_Ads");
                });

            modelBuilder.Entity("AdvertSystem.Models.AnnonsorerModel", b =>
                {
                    b.Property<int>("An_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("An_Id"), 1L, 1);

                    b.Property<int?>("An_CoIdCo_Id")
                        .HasColumnType("int");

                    b.Property<int?>("An_SubId")
                        .HasColumnType("int");

                    b.HasKey("An_Id");

                    b.HasIndex("An_CoIdCo_Id");

                    b.ToTable("Tbl_Annonsorer");
                });

            modelBuilder.Entity("AdvertSystem.Models.CompanyModel", b =>
                {
                    b.Property<int>("Co_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Co_Id"), 1L, 1);

                    b.Property<string>("Co_BillCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Co_BillPostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Co_BillStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Co_City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Co_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Co_OrgId")
                        .HasColumnType("int");

                    b.Property<int>("Co_PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Co_Steet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Co_Telephone")
                        .HasColumnType("int");

                    b.HasKey("Co_Id");

                    b.ToTable("Tbl_Companies");
                });

            modelBuilder.Entity("AdvertSystem.Models.AdModel", b =>
                {
                    b.HasOne("AdvertSystem.Models.AnnonsorerModel", "Ads_Annonsor")
                        .WithMany()
                        .HasForeignKey("Ads_AnnonsorAn_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ads_Annonsor");
                });

            modelBuilder.Entity("AdvertSystem.Models.AnnonsorerModel", b =>
                {
                    b.HasOne("AdvertSystem.Models.CompanyModel", "An_CoId")
                        .WithMany()
                        .HasForeignKey("An_CoIdCo_Id");

                    b.Navigation("An_CoId");
                });
#pragma warning restore 612, 618
        }
    }
}
